### ISSUE TITLE
What is the status of of the project?

### ISSUE THREAD

**Issue by meteozond** [regit/pynetfilter_conntrack#2]
1. Looks like [Official page](http://software.inl.fr/trac/trac.cgi/wiki/pynetfilter_conntrack) is down. Is it an official repo?
2. `setup.py` points to the missing `README` (after the renaming it into the `README.rst`).
3. 0.5 version is released but the latest the [pypi repo version is 0.4.2](https://pypi.python.org/pypi/pynetfilter_conntrack).
4. 0.5 version is trying to import missing `nfct_conntrack_compare` sysmbol.
5. 0.4.2 randomly fails into the `maximum recursion depth exceeded`.

**Comment by regit** [comment]
This github repo aims at avoiding it to become a death project following death of sponsoring company. I will try to fix the points but PR are welcome.

**Comment by regit** [comment]
1. one of the last remaining
2. fixed and pushed
3. need to check if I can do the upload
4. fixed and pushed
5. won't fix an old one

**Comment by regit** [comment]
hello @haypo, could you give me access to pypi repo for pynetfilter_conntrack, you are mentioned in the list of admin ?

**Comment by vstinner** [comment]
> hello @haypo, could you give me access to pypi repo for pynetfilter_conntrack, you are mentioned in the list of admin ?

Hi Eric! What's up?

I just added you as an owner of the project. In the meanwhile, I removed my role from the project. I'm not more interested to work on it.

**Comment by regit** [comment]
Thanks @haypo! Uploaded a new version 6 years after l previous one ;)

Going fine. Currently at RMLL and doing a bit of coding during the conf.

**Comment by meteozond** [comment]
You are... awesome, guys!
![You are... awesome](http://replygif.net/i/904.gif)
